name: Issue Feature Progress

on:
  issues:
    types: [labeled]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Progress'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, I see your question, If I have time, I will consider developing this function. Of course, you are also welcome to propose PR.
            你好 @${{ github.event.issue.user.login }}, 我已经了解你的问题, 如果有空的话, 我会考虑开发这个功能, 当然, 也欢迎你提PR。
